<!DOCTYPE html>
<html <?php language_attributes(); ?>>

	<!-- ensure iframe links are opened in a new tab in the parent uless this is a scorm page builder -->

<?php if(get_field('field_5d96ba9048134')): ?>
	<div id="dev-notification" class="col-12 text-light bg-danger text-center p-3 zindex-indev"><strong> Page is in development - do not review. </strong>

		<?php if(get_field('field_5d96ba9048134')): ?>
			<?php echo "Developer Note: "; ?>
<?php
		echo the_field('field_5d96d31960caa'); ?>
<?php endif;
?>
	</div>

<?php endif;
?>




<style>
<?php
/* Custom CSS */
the_field('field_5b2849d5b9d0c'); ?>

</style>


	<!--
 __      ________   _____            _               _______
 \ \    / /  ____| |  __ \          (_)             |__   __|
  \ \  / /| |__    | |  | | ___  ___ _  __ _ _ __      | | ___  __ _ _ __ ___
   \ \/ / |  __|   | |  | |/ _ \/ __| |/ _` | '_ \     | |/ _ \/ _` | '_ ` _ \
    \  /  | |____  | |__| |  __/\__ \ | (_| | | | |    | |  __/ (_| | | | | | |
     \/   |______| |_____/ \___||___/_|\__, |_| |_|    |_|\___|\__,_|_| |_| |_|
                                        __/ |
                                       |___/
This custom content was generated by the RMIT Vocational Education Design team - https://emedia.rmit.edu.au/oedvedesign/
-->


<!-- aged care forms-->


<!DOCTYPE html.no-js(lang='en-au' )>




<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="author" content="RMITs Vocational Education Design Team" />
    <meta name="description" content="A training resource for teaching digital literacy in health care delivery" />
    <meta name="keywords" content="Aged Care, Digital Literacy" />
    <meta charset="UTF-8" />
    <title>Bagwan Aged Care Facility</title>&#x9;
    <link rel="stylesheet" type="text/css" href="<?php echo get_stylesheet_directory_uri(); ?>/aged_care_forms/css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="<?php echo get_stylesheet_directory_uri(); ?>/aged_care_forms/css/all.css" />
    <link rel="stylesheet" type="text/css" href="<?php echo get_stylesheet_directory_uri(); ?>/aged_care_forms/css/sumoselect.min.css" />
    <link rel="stylesheet" type="text/css" href="<?php echo get_stylesheet_directory_uri(); ?>/aged_care_forms/css/main.css" />
    <?php wp_head(); ?>
</head><!-- Header-->
<div class="row p-2 mb-5 ml-0 mr-0  position-absolute w-100">
    <div class="container"> <img class="logo" src="<?php echo get_stylesheet_directory_uri(); ?>/vwp/img/splash-bagwan.png" alt="Bagwan Aged Care Facility" /><span class="float-right m-3" style="font-size: 1.7rem;
    color: #000094;
    position: relative;
    top: 6px;
    font-weight: 600;">Patient Management System</span>
    <!--
    <a
            class=" float-right mt-3" href="<?php echo get_site_url(); ?>/patient-management-system">Back to all forms</a></div>
</div>-->